CREATE TABLE PostComments (
      Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
      UserId INT NOT NULL,
      PostId UNIQUEIDENTIFIER NOT NULL,
      ParentId UNIQUEIDENTIFIER NULL,
      Comment NVARCHAR(MAX) NOT NULL,
      CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
      UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
      FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
      FOREIGN KEY (PostId) REFERENCES Posts(Id) ON DELETE CASCADE,
      FOREIGN KEY (ParentId) REFERENCES PostComments(Id)
);
