CREATE TABLE PostLikes (
       UserId INT NOT NULL,
       PostId UNIQUEIDENTIFIER NOT NULL,
       LikedAt DATETIME NOT NULL DEFAULT GETDATE(),
       PRIMARY KEY (UserId, PostId),
       FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
       FOREIGN KEY (PostId) REFERENCES Posts(Id) ON DELETE CASCADE
);
