CREATE TABLE Users (
   Id INT PRIMARY KEY IDENTITY(1,1),
   Username NVARCHAR(100) NOT NULL,
   Name NVARCHAR(100) NOT NULL,
   Surname NVARCHAR(100) NOT NULL,
   MiddleName NVARCHAR(100) NULL,
   Email NVARCHAR(255) NOT NULL UNIQUE,
   Password NVARCHAR(255) NOT NULL,
   Role NVARCHAR(50) NOT NULL DEFAULT 'user',
   PhoneNumber NVARCHAR(20) NULL,
   City NVARCHAR(100) NULL,
   State NVARCHAR(100) NULL,
   Country NVARCHAR(100) NULL,
   CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
   UpdatedAt DATETIME NULL,
   ProfilePicture NVARCHAR(MAX) NULL,
   GenerationToken INT NOT NULL DEFAULT 10
);